BindInterface All
BindPort 10021
CommandTimeout 300
ConnectTimeout 15
MaxConnections 240
LookupHosts On

<User "asdf">
Password "asdf"
Mount "/" "C:\\Users\\Jazzlife\\Desktop\\HyOn_2.1.14\\HyonServer\\bin\\Debug\\Pages"
Allow / All
</User>
